server:
  port: 9090  # Your gateway port


spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-connect
            client-secret: RyDc7TGkZtLi4nBa2Ys1WxW80DyAHhK6
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/callback"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth-gateway
            user-name-attribute: preferred_username
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: demo-customer
              uri: http://localhost:9091
              predicates:
                - Path=/api/customrs/**
              filters:
                - TokenRelay

# application.yml
logging:
  level:
    # Spring Security
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG

    # OAuth2 Specific
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG

    # Gateway
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.gateway.handler: TRACE

    # Web and Session
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
    org.springframework.web.session: DEBUG
    
    # HTTP Client
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.http.client: DEBUG

    # Additional Security
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security.config: DEBUG